#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'solve' function below.
#
# The function accepts following parameters:
#  1. DOUBLE meal_cost
#  2. INTEGER tip_percent
#  3. INTEGER tax_percent
#

def solve(meal_cost, tip_percent, tax_percent):
    # Write your code here
    #print(meal_cost)
    tip=((meal_cost*tip_percent))/100
    #tp1=tip/100
     
    #print(tip)
    tax=(tax_percent*tip_percent)/100
    #print(tax)
    sum=meal_cost+tip+tax
    print(round(sum))

if __name__ == '__main__':
    meal_cost = float(input().strip())

    tip_percent = int(input().strip())

    tax_percent = int(input().strip())

    solve(meal_cost, tip_percent, tax_percent)
